import { mutation } from "./_generated/server";

// Seed database with initial data
export const seedDatabase = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existingProjects = await ctx.db.query("projects").collect();
    if (existingProjects.length > 0) {
      return { message: "Database already seeded", count: existingProjects.length };
    }

    const now = Date.now();

    // Seed 10 real Web3 projects
    const projects = [
      {
        name: "Uniswap",
        tagline: "Leading decentralized trading protocol",
        description: "Uniswap is the largest decentralized exchange (DEX) on Ethereum, enabling trustless token swaps through automated liquidity pools. With over $4B in TVL, Uniswap V3 introduces concentrated liquidity for improved capital efficiency.",
        logo: "https://cryptologos.cc/logos/uniswap-uni-logo.png",
        coverImage: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200",
        category: "DeFi",
        tags: ["DEX", "AMM", "Liquidity", "Trading"],
        chain: "Ethereum",
        launchDate: "2018-11-02",
        verified: true,
        featured: true,
        tvl: "$4.2B",
        users: "3.5M+",
        transactions: "200M+",
        growth: 15.2,
        tokenSymbol: "UNI",
        tokenAddress: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
        tokenPrice: "$6.42",
        tokenMarketCap: "$4.8B",
        tokenChange24h: 3.5,
        website: "https://uniswap.org",
        twitter: "https://twitter.com/Uniswap",
        github: "https://github.com/Uniswap",
        ownerWallet: "0x1234567890123456789012345678901234567890",
        upvoteCount: 1247,
        reviewCount: 89,
        averageRating: 4.7,
        createdAt: now - 30 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "Aave",
        tagline: "Non-custodial liquidity protocol",
        description: "Aave is a decentralized lending protocol that allows users to lend and borrow cryptocurrencies without intermediaries. Features flash loans, rate switching, and over 30 supported assets across multiple chains.",
        logo: "https://cryptologos.cc/logos/aave-aave-logo.png",
        coverImage: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=1200",
        category: "DeFi",
        tags: ["Lending", "Borrowing", "Flash Loans", "Multi-chain"],
        chain: "Ethereum",
        launchDate: "2020-01-08",
        verified: true,
        featured: true,
        tvl: "$5.8B",
        users: "500K+",
        transactions: "15M+",
        growth: 12.8,
        tokenSymbol: "AAVE",
        tokenAddress: "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9",
        tokenPrice: "$172.50",
        tokenMarketCap: "$2.5B",
        tokenChange24h: 5.2,
        website: "https://aave.com",
        twitter: "https://twitter.com/AaveAave",
        github: "https://github.com/aave",
        ownerWallet: "0x2345678901234567890123456789012345678901",
        upvoteCount: 1089,
        reviewCount: 76,
        averageRating: 4.6,
        createdAt: now - 28 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "OpenSea",
        tagline: "World's first and largest NFT marketplace",
        description: "OpenSea is the leading NFT marketplace where users can discover, collect, and sell unique digital items. Supporting ERC-721 and ERC-1155 standards with gasless trading via Seaport protocol.",
        logo: "https://storage.googleapis.com/opensea-static/Logomark/Logomark-Blue.png",
        coverImage: "https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?w=1200",
        category: "NFT",
        tags: ["Marketplace", "NFTs", "Collectibles", "Art"],
        chain: "Ethereum",
        launchDate: "2017-12-20",
        verified: true,
        featured: true,
        tvl: "N/A",
        users: "2M+",
        transactions: "100M+",
        growth: 8.5,
        website: "https://opensea.io",
        twitter: "https://twitter.com/opensea",
        github: "https://github.com/ProjectOpenSea",
        ownerWallet: "0x3456789012345678901234567890123456789012",
        upvoteCount: 892,
        reviewCount: 124,
        averageRating: 4.3,
        createdAt: now - 25 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "Lens Protocol",
        tagline: "Decentralized social graph",
        description: "Lens Protocol is a composable and decentralized social graph built on Polygon. Users own their content, followers, and social connections as NFTs, enabling true ownership of social identity.",
        logo: "https://lens.xyz/logo.png",
        coverImage: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200",
        category: "Social",
        tags: ["Social", "Web3", "NFTs", "Identity"],
        chain: "Polygon",
        launchDate: "2022-05-18",
        verified: true,
        featured: false,
        tvl: "N/A",
        users: "500K+",
        transactions: "25M+",
        growth: 22.4,
        website: "https://lens.xyz",
        twitter: "https://twitter.com/LensProtocol",
        github: "https://github.com/lens-protocol",
        ownerWallet: "0x4567890123456789012345678901234567890123",
        upvoteCount: 743,
        reviewCount: 52,
        averageRating: 4.5,
        createdAt: now - 22 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "Chainlink",
        tagline: "Decentralized oracle network",
        description: "Chainlink provides reliable, tamper-proof data feeds for complex smart contracts on any blockchain. Powers DeFi, gaming, insurance, and enterprise applications with secure off-chain data.",
        logo: "https://cryptologos.cc/logos/chainlink-link-logo.png",
        coverImage: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1200",
        category: "Infrastructure",
        tags: ["Oracles", "Data Feeds", "Cross-chain", "Infrastructure"],
        chain: "Ethereum",
        launchDate: "2017-09-19",
        verified: true,
        featured: false,
        tvl: "$15B+",
        users: "1,500+",
        transactions: "7B+",
        growth: 18.3,
        tokenSymbol: "LINK",
        tokenAddress: "0x514910771af9ca656af840dff83e8264ecf986ca",
        tokenPrice: "$14.25",
        tokenMarketCap: "$8.5B",
        tokenChange24h: 2.8,
        website: "https://chain.link",
        twitter: "https://twitter.com/chainlink",
        github: "https://github.com/smartcontractkit",
        ownerWallet: "0x5678901234567890123456789012345678901234",
        upvoteCount: 956,
        reviewCount: 67,
        averageRating: 4.8,
        createdAt: now - 20 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "The Graph",
        tagline: "Indexing protocol for querying blockchain data",
        description: "The Graph is an indexing protocol for organizing blockchain data. It enables developers to build and publish open APIs called subgraphs, making blockchain data easily accessible via GraphQL.",
        logo: "https://cryptologos.cc/logos/the-graph-grt-logo.png",
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200",
        category: "Infrastructure",
        tags: ["Indexing", "GraphQL", "Data", "Developer Tools"],
        chain: "Ethereum",
        launchDate: "2020-12-17",
        verified: true,
        featured: false,
        tvl: "N/A",
        users: "30K+",
        transactions: "500M+",
        growth: 14.7,
        tokenSymbol: "GRT",
        tokenAddress: "0xc944e90c64b2c07662a292be6244bdf05cda44a7",
        tokenPrice: "$0.24",
        tokenMarketCap: "$2.2B",
        tokenChange24h: 1.2,
        website: "https://thegraph.com",
        twitter: "https://twitter.com/graphprotocol",
        github: "https://github.com/graphprotocol",
        ownerWallet: "0x6789012345678901234567890123456789012345",
        upvoteCount: 621,
        reviewCount: 43,
        averageRating: 4.4,
        createdAt: now - 18 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "Arbitrum One",
        tagline: "Optimistic rollup scaling solution",
        description: "Arbitrum is a Layer 2 scaling solution for Ethereum that significantly reduces costs and increases transaction speed while maintaining Ethereum's security. Compatible with existing Ethereum tools.",
        logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
        coverImage: "https://images.unsplash.com/photo-1639762681057-408e52192e55?w=1200",
        category: "Infrastructure",
        tags: ["Layer 2", "Scaling", "Rollup", "Low Fees"],
        chain: "Arbitrum",
        launchDate: "2021-08-31",
        verified: true,
        featured: false,
        tvl: "$2.4B",
        users: "1.2M+",
        transactions: "500M+",
        growth: 28.5,
        tokenSymbol: "ARB",
        tokenAddress: "0x912ce59144191c1204e64559fe8253a0e49e6548",
        tokenPrice: "$0.78",
        tokenMarketCap: "$3.1B",
        tokenChange24h: 4.1,
        website: "https://arbitrum.io",
        twitter: "https://twitter.com/arbitrum",
        github: "https://github.com/OffchainLabs",
        ownerWallet: "0x7890123456789012345678901234567890123456",
        upvoteCount: 834,
        reviewCount: 58,
        averageRating: 4.6,
        createdAt: now - 15 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "Base",
        tagline: "Ethereum L2 built by Coinbase",
        description: "Base is a secure, low-cost, builder-friendly Ethereum L2 built to bring the next billion users onchain. Built on the Optimism stack with deep Coinbase integration.",
        logo: "https://avatars.githubusercontent.com/u/108554348",
        coverImage: "https://images.unsplash.com/photo-1642104704074-907c0698cbd9?w=1200",
        category: "Infrastructure",
        tags: ["Layer 2", "Scaling", "Coinbase", "Developer Friendly"],
        chain: "Base",
        launchDate: "2023-08-09",
        verified: true,
        featured: false,
        tvl: "$1.8B",
        users: "800K+",
        transactions: "150M+",
        growth: 42.3,
        website: "https://base.org",
        twitter: "https://twitter.com/base",
        github: "https://github.com/base-org",
        ownerWallet: "0x8901234567890123456789012345678901234567",
        upvoteCount: 1124,
        reviewCount: 72,
        averageRating: 4.7,
        createdAt: now - 12 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "Axie Infinity",
        tagline: "Play-to-earn blockchain game",
        description: "Axie Infinity is a Pokemon-inspired blockchain game where players collect, breed, and battle creatures called Axies. Pioneer in play-to-earn gaming with a thriving economy and esports scene.",
        logo: "https://cryptologos.cc/logos/axie-infinity-axs-logo.png",
        coverImage: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200",
        category: "Gaming",
        tags: ["Gaming", "NFT", "Play-to-Earn", "Metaverse"],
        chain: "Ethereum",
        launchDate: "2018-03-01",
        verified: true,
        featured: false,
        tvl: "N/A",
        users: "2M+",
        transactions: "500M+",
        growth: 6.8,
        tokenSymbol: "AXS",
        tokenAddress: "0xbb0e17ef65f82ab018d8edd776e8dd940327b28b",
        tokenPrice: "$7.12",
        tokenMarketCap: "$1.1B",
        tokenChange24h: -2.1,
        website: "https://axieinfinity.com",
        twitter: "https://twitter.com/AxieInfinity",
        github: "https://github.com/axieinfinity",
        ownerWallet: "0x9012345678901234567890123456789012345678",
        upvoteCount: 567,
        reviewCount: 94,
        averageRating: 4.2,
        createdAt: now - 10 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
      {
        name: "MakerDAO",
        tagline: "Decentralized stablecoin protocol",
        description: "MakerDAO is the creator of DAI, a decentralized stablecoin soft-pegged to USD. Users can lock collateral to generate DAI and participate in governance to manage the protocol.",
        logo: "https://cryptologos.cc/logos/maker-mkr-logo.png",
        coverImage: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=1200",
        category: "DAO",
        tags: ["Stablecoin", "DAO", "Governance", "DeFi"],
        chain: "Ethereum",
        launchDate: "2017-12-18",
        verified: true,
        featured: false,
        tvl: "$5.2B",
        users: "50K+",
        transactions: "10M+",
        growth: 9.2,
        tokenSymbol: "MKR",
        tokenAddress: "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2",
        tokenPrice: "$1,542.00",
        tokenMarketCap: "$1.4B",
        tokenChange24h: 1.8,
        website: "https://makerdao.com",
        twitter: "https://twitter.com/MakerDAO",
        github: "https://github.com/makerdao",
        ownerWallet: "0x0123456789012345678901234567890123456789",
        upvoteCount: 723,
        reviewCount: 61,
        averageRating: 4.5,
        createdAt: now - 8 * 24 * 60 * 60 * 1000,
        updatedAt: now,
      },
    ];

    // Insert all projects
    const projectIds = [];
    for (const project of projects) {
      const id = await ctx.db.insert("projects", project);
      projectIds.push(id);
    }

    // Add sample forum posts
    const forumPosts = [
      {
        title: "The Future of Decentralized Finance in 2024",
        excerpt: "Exploring the trends and innovations shaping DeFi this year...",
        content: "Decentralized Finance has evolved dramatically over the past few years. In 2024, we're seeing increased adoption of Layer 2 solutions, improved UX, and institutional involvement. This post explores the key trends...",
        authorWallet: "0x1111111111111111111111111111111111111111",
        authorName: "DeFi Explorer",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=defi",
        category: "DeFi",
        coverImage: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800",
        readTime: "5 min read",
        likeCount: 42,
        commentCount: 12,
        createdAt: now - 5 * 24 * 60 * 60 * 1000,
      },
      {
        title: "Building on Base: A Developer's Guide",
        excerpt: "Everything you need to know about developing on Base L2...",
        content: "Base has emerged as one of the most developer-friendly Layer 2 solutions. This comprehensive guide covers everything from setting up your environment to deploying your first contract...",
        authorWallet: "0x2222222222222222222222222222222222222222",
        authorName: "BuilderDAO",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=builder",
        category: "Infrastructure",
        coverImage: "https://images.unsplash.com/photo-1642104704074-907c0698cbd9?w=800",
        readTime: "8 min read",
        likeCount: 67,
        commentCount: 23,
        createdAt: now - 3 * 24 * 60 * 60 * 1000,
      },
      {
        title: "NFT Market Analysis: Trends and Insights",
        excerpt: "A deep dive into the current state of the NFT marketplace...",
        content: "The NFT market has matured significantly. This analysis covers trading volumes, emerging trends, and what to watch for in the coming months...",
        authorWallet: "0x3333333333333333333333333333333333333333",
        authorName: "NFT Analyst",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nft",
        category: "NFT",
        likeCount: 34,
        commentCount: 8,
        createdAt: now - 1 * 24 * 60 * 60 * 1000,
      },
    ];

    for (const post of forumPosts) {
      await ctx.db.insert("forumPosts", post);
    }

    return {
      message: "Database seeded successfully",
      projects: projectIds.length,
      forumPosts: forumPosts.length,
    };
  },
});
