import { MockProject, ProjectCategory, ForumPost } from './types';

const MOCK_REVIEWS = [
  { id: '1', user: 'CryptoKing', avatar: 'https://randomuser.me/api/portraits/men/32.jpg', rating: 5, comment: 'Absolutely game changing protocol. The UI is silky smooth.', date: '2 days ago' },
  { id: '2', user: 'Web3Witch', avatar: 'https://randomuser.me/api/portraits/women/44.jpg', rating: 4, comment: 'Great yields but transaction fees on ETH mainnet are still high. L2 support is great though.', date: '1 week ago' },
  { id: '3', user: 'AnonDev', avatar: 'https://randomuser.me/api/portraits/men/85.jpg', rating: 5, comment: 'Audited and secure. That is all that matters to me.', date: '2 weeks ago' },
  { id: '4', user: 'SatoshiFan', avatar: 'https://randomuser.me/api/portraits/men/12.jpg', rating: 5, comment: 'To the moon! 🚀', date: '3 weeks ago' }
];

const MOCK_SCREENSHOTS = [
  'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&q=80',
  'https://images.unsplash.com/photo-1639815188546-c43c240ff4df?w=800&q=80',
  'https://images.unsplash.com/photo-1639322537228-ad7116995e5d?w=800&q=80'
];

export const MOCK_FORUM_POSTS: ForumPost[] = [
  // Blog Style Posts (integrated as forum posts)
  {
      id: 'b1',
      title: 'Mastering DeFi: Strategies for 2025',
      excerpt: 'Explore advanced yield farming strategies and how to mitigate impermanent loss in volatile markets.',
      content: 'DeFi is moving fast. The strategies that worked in 2023 are obsolete. In this deep dive, we explore how delta-neutral strategies using GLP and other derivatives are becoming the standard for institutional-grade yield farming...',
      coverImage: 'https://images.unsplash.com/photo-1639322537228-ad7116995e5d?w=800&q=80',
      author: 'Alex Chain',
      avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
      date: 'Oct 24, 2024',
      readTime: '5 min read',
      category: 'Trading',
      likes: 245,
      comments: 18,
      commentsList: [
        { id: 'c1', author: 'YieldFarmer99', avatar: 'https://randomuser.me/api/portraits/women/12.jpg', content: 'Great article. GLP has been solid.', date: '1 day ago', likes: 5 }
      ]
  },
  {
      id: 'b2',
      title: 'Identifying the Next 100x Gem',
      excerpt: 'A comprehensive guide on how to analyze on-chain metrics, team activity, and community sentiment.',
      content: 'Everyone wants the 100x, but few do the work. We break down the 5 pillars of fundamental analysis: 1. Team Vesting Schedules, 2. GitHub Activity, 3. Community Engagement metrics...',
      coverImage: 'https://images.unsplash.com/photo-1621504450162-e15296cc6cce?w=800&q=80',
      author: 'Sarah Satoshi',
      avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
      date: 'Oct 22, 2024',
      readTime: '8 min read',
      category: 'Analysis',
      likes: 532,
      comments: 45,
      commentsList: []
  },
  {
      id: 'b3',
      title: 'The Rise of GameFi on Solana',
      excerpt: 'Why high throughput blockchains are essential for the next generation of on-chain gaming.',
      content: 'Solana is positioning itself as the premier chain for gaming. With Firedancer coming, the TPS will enable fully on-chain logic that was previously impossible...',
      coverImage: 'https://images.unsplash.com/photo-1555861496-0666c8981751?w=800&q=80',
      author: 'Pixel Pete',
      avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
      date: 'Oct 20, 2024',
      readTime: '4 min read',
      category: 'Gaming',
      likes: 189,
      comments: 12,
      commentsList: []
  },
  // Regular Forum Posts
  {
    id: '1',
    title: 'The Future of Yield Aggregation: AI vs Manual Strategies',
    excerpt: 'With protocols like Nebula Fi launching, we are seeing a shift towards automated strategies. Is this safe?',
    content: 'Yield aggregation has evolved significantly. Initially, we had simple auto-compounders. Now, with AI-driven strategies like those seen in Nebula Fi, the question arises: are we creating black boxes that are too complex to audit? \n\nI believe AI is the future, but we need standardization in how these agents report their activity on-chain. What do you guys think?',
    author: 'DeFi_Wizard',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    category: 'Technical',
    date: '2 hours ago',
    likes: 45,
    comments: 2,
    commentsList: [
        { id: 'c1', author: 'YieldFarmer99', avatar: 'https://randomuser.me/api/portraits/women/12.jpg', content: 'Great point. Transparency is key.', date: '1 hour ago', likes: 5 },
        { id: 'c2', author: 'SecAudit', avatar: 'https://randomuser.me/api/portraits/men/44.jpg', content: 'AI models can be verified using ZK proofs. That is the way forward.', date: '30 mins ago', likes: 12 }
    ]
  },
  {
    id: '2',
    title: 'Layer 2 scaling solutions comparison 2024',
    excerpt: 'Arbitrum vs Optimism vs Base. Who is winning the liquidity war?',
    content: 'I have been analyzing the TVL growth across major L2s. Base is catching up fast due to the Coinbase integration, but Arbitrum still holds the DeFi crown. Optimism is building a superchain. \n\nHere are my stats for Q3...',
    author: 'ChainAnalyst',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    category: 'Analysis',
    date: '5 hours ago',
    likes: 120,
    comments: 1,
    commentsList: [
        { id: 'c3', author: 'BaseMaxi', avatar: 'https://randomuser.me/api/portraits/men/22.jpg', content: 'Base is inevitable.', date: '2 hours ago', likes: 8 }
    ]
  },
   {
    id: '3',
    title: 'Proposal: Standardizing NFT metadata for Gaming',
    excerpt: 'We need a unified standard for cross-game asset interoperability.',
    content: 'If we want true metaverse interoperability, a sword in Game A should be usable in Game B. Currently, metadata standards are all over the place. I propose a new ERC extension...',
    author: 'GameDev_X',
    avatar: 'https://randomuser.me/api/portraits/men/85.jpg',
    category: 'Governance',
    date: '1 day ago',
    likes: 89,
    comments: 0,
    commentsList: []
  }
];

export const MOCK_PROJECTS: MockProject[] = [
  {
    id: '1',
    name: 'Nebula Fi',
    tagline: 'Next-Gen Yield Aggregator with AI Strategy',
    description: 'Nebula Fi leverages machine learning to optimize yield farming strategies across multiple chains in real-time. Experience the future of passive income with verified safe vaults and automated rebalancing. Our protocol constantly scans for the best APY across Aave, Compound, and Curve, automatically moving your funds to the highest performing pools without you lifting a finger.',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
    category: ProjectCategory.DeFi,
    tags: ['Yield', 'AI', 'Multi-chain'],
    stats: {
      tvl: '$12.4M',
      users: '4.2k',
      transactions: '150k+',
      growth: 12.5,
    },
    rating: 4.8,
    reviewCount: 342,
    verified: true,
    team: [
      { name: 'Alex Doe', role: 'CTO', avatar: 'https://randomuser.me/api/portraits/men/1.jpg' },
      { name: 'Sarah Smith', role: 'Lead Dev', avatar: 'https://randomuser.me/api/portraits/women/2.jpg' }
    ],
    launchDate: '2024-01-15',
    chain: 'Arbitrum',
    featured: true,
    upvotes: 420,
    screenshots: MOCK_SCREENSHOTS,
    tokenInfo: {
        symbol: 'NEB',
        address: '0x1234...5678',
        price: '$4.20',
        marketCap: '$42M',
        change24h: 5.4
    },
    reviews: MOCK_REVIEWS,
    auditUrl: 'https://certik.com'
  },
  {
    id: '2',
    name: 'Pixel Quest',
    tagline: 'MMORPG built fully on-chain',
    description: 'A retro-style MMORPG where every item, quest, and achievement is an NFT. Trade, battle, and explore a vast procedural world with thousands of other players.',
    logo: 'https://images.unsplash.com/photo-1555861496-0666c8981751?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=400&fit=crop',
    category: ProjectCategory.Gaming,
    tags: ['P2E', 'NFT', 'Metaverse'],
    stats: {
      users: '12k',
      transactions: '890k',
      growth: 45.2,
    },
    rating: 4.5,
    reviewCount: 1205,
    verified: true,
    team: [
      { name: 'Jin Yang', role: 'Producer', avatar: 'https://randomuser.me/api/portraits/men/3.jpg' }
    ],
    launchDate: '2023-11-20',
    chain: 'Polygon',
    featured: true,
    upvotes: 315,
    screenshots: ['https://images.unsplash.com/photo-1593305841991-05c29736f87e?w=800', 'https://images.unsplash.com/photo-1614726365723-49cfa117904c?w=800'],
    tokenInfo: {
        symbol: 'PIXEL',
        address: '0x9876...5432',
        price: '$0.15',
        marketCap: '$12M',
        change24h: -2.1
    },
    reviews: [MOCK_REVIEWS[0]],
  },
  {
    id: '3',
    name: 'Agora DAO',
    tagline: 'Decentralized Governance Tooling',
    description: 'The easiest way to spin up a DAO. Voting, treasury management, and proposal drafting all in one seamless dashboard. Empower your community today.',
    logo: 'https://images.unsplash.com/photo-1622630998477-20aa696fab05?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=400&fit=crop',
    category: ProjectCategory.DAO,
    tags: ['Governance', 'Tools'],
    stats: {
      tvl: '$45M',
      users: '850',
      transactions: '5k',
      growth: 5.4,
    },
    rating: 4.9,
    reviewCount: 89,
    verified: false,
    team: [],
    launchDate: '2024-03-01',
    chain: 'Ethereum',
    featured: true,
    upvotes: 290,
    screenshots: MOCK_SCREENSHOTS,
    reviews: MOCK_REVIEWS,
  },
  {
    id: '4',
    name: 'Lens Social',
    tagline: 'Own your social graph',
    description: 'A decentralized social media layer. Build your profile, follow creators, and own your data forever. No more censorship, just pure connection.',
    logo: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&h=400&fit=crop',
    category: ProjectCategory.Social,
    tags: ['Social', 'Web3', 'Identity'],
    stats: {
      users: '150k',
      transactions: '2M+',
      growth: 8.9,
    },
    rating: 4.6,
    reviewCount: 5600,
    verified: true,
    team: [],
    launchDate: '2023-05-15',
    chain: 'Polygon',
    upvotes: 560,
    screenshots: MOCK_SCREENSHOTS,
    reviews: MOCK_REVIEWS,
  },
  {
    id: '5',
    name: 'Base Swap',
    tagline: 'Fastest DEX on Base',
    description: 'Instant swaps with near-zero gas fees. The premier liquidity layer for the Base ecosystem. Trade tokens instantly and securely.',
    logo: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1642104704074-907c0698cbd9?w=800&h=400&fit=crop',
    category: ProjectCategory.DeFi,
    tags: ['DEX', 'AMM'],
    stats: {
      tvl: '$8.2M',
      users: '9.1k',
      transactions: '250k',
      growth: 18.1,
    },
    rating: 4.3,
    reviewCount: 210,
    verified: true,
    team: [],
    launchDate: '2024-02-10',
    chain: 'Base',
    upvotes: 180,
    screenshots: MOCK_SCREENSHOTS,
    reviews: MOCK_REVIEWS,
  },
  {
    id: '6',
    name: 'Solana Speed',
    tagline: 'High frequency trading bot',
    description: 'Execute trades at the speed of light on Solana. Our bot ensures you never miss a sniper entry again.',
    logo: 'https://images.unsplash.com/photo-1640161704729-cbe966a08476?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
    category: ProjectCategory.DeFi,
    tags: ['Trading', 'Bot', 'Solana'],
    stats: {
      tvl: '$1M',
      users: '500',
      transactions: '1.2M',
      growth: 60.5,
    },
    rating: 4.1,
    reviewCount: 55,
    verified: false,
    team: [],
    launchDate: '2024-01-20',
    chain: 'Solana',
    upvotes: 95,
    screenshots: MOCK_SCREENSHOTS,
    reviews: MOCK_REVIEWS,
  },
  {
    id: '7',
    name: 'Art Blocks',
    tagline: 'Generative Content',
    description: 'A platform for truly programmable generative art. Each output is unique and generated on demand.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1618172193763-c511deb635ca?w=800&h=400&fit=crop',
    category: ProjectCategory.NFT,
    tags: ['Art', 'Generative'],
    stats: {
      users: '45k',
      transactions: '100k',
      growth: 2.3,
    },
    rating: 4.9,
    reviewCount: 3000,
    verified: true,
    team: [],
    launchDate: '2021-06-15',
    chain: 'Ethereum',
    upvotes: 800,
    screenshots: MOCK_SCREENSHOTS,
    reviews: MOCK_REVIEWS,
  },
  {
    id: '8',
    name: 'Brain Chain',
    tagline: 'AI Compute Marketplace',
    description: 'Rent out your GPU for AI training or access decentralized compute power at a fraction of the cost.',
    logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=400&fit=crop',
    category: ProjectCategory.AI,
    tags: ['AI', 'DePIN', 'Infrastructure'],
    stats: {
      tvl: '$20M',
      users: '2.3k',
      transactions: '45k',
      growth: 33.3,
    },
    rating: 4.7,
    reviewCount: 156,
    verified: true,
    team: [],
    launchDate: '2024-03-10',
    chain: 'Solana',
    upvotes: 210,
    screenshots: MOCK_SCREENSHOTS,
    reviews: MOCK_REVIEWS,
  }
];
